const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

const svgPath = path.join(__dirname, '../resources/icon.svg');
const outputDir = path.join(__dirname, '../resources');

// Create a rounded square icon function
async function createIcons() {
  // Generate PNG at different sizes
  const sizes = [16, 32, 64, 128, 256, 512];

  for (const size of sizes) {
    await sharp(svgPath)
      .resize(size, size)
      .png()
      .toFile(path.join(outputDir, `icon-${size}x${size}.png`));
    console.log(`Generated ${size}x${size} PNG`);
  }

  // Generate a 512x512 base icon
  await sharp(svgPath)
    .resize(512, 512)
    .png()
    .toFile(path.join(outputDir, 'icon.png'));
  console.log('Generated icon.png');

  // For .ico (Windows) - use the 256x256 PNG
  // Note: true .ico requires special format, but many Electron setups accept PNG
  await sharp(svgPath)
    .resize(256, 256)
    .png()
    .toFile(path.join(outputDir, 'icon.ico'));
  console.log('Generated icon.ico (PNG format)');

  // For .icns (Mac) - electron-builder will handle this from icon.png
  console.log('Note: .icns will be generated by electron-builder from icon.png');

  console.log('Icons generated successfully!');
}

createIcons().catch(console.error);
